
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  Member: 'Member',
  Admin: 'Admin'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const Category = {
  WebDev: 'WebDev',
  Lifestyle: 'Lifestyle',
  GeneralTech: 'GeneralTech',
  Tutorials: 'Tutorials',
  Security: 'Security',
  Gaming: 'Gaming',
  Entertainment: 'Entertainment'
} as const

export type Category = (typeof Category)[keyof typeof Category]
